apiVersion: v2
name: firefly-iii-stack
version: 0.7.2
description: Installs Firefly III stack (db, app, importer)
type: application
dependencies:
- name: firefly-db
  version: 0.1.0
  condition: firefly-db.enabled
  repository: https://firefly-iii.github.io/kubernetes/
- name: firefly-iii
  version: 1.4.0
  condition: firefly-iii.enabled
  repository: https://phmatos.github.io/kubernetes/
- name: importer
  version: 1.3.1
  condition: importer.enabled
  repository: https://phmatos.github.io/kubernetes/
home: https://github.com/phmatos/kubernetes
sources:
  - https://github.com/phmatos/kubernetes
maintainers:
  - name: morremeyer
    email: firefly-iii@mor.re
icon: https://raw.githubusercontent.com/firefly-iii/firefly-iii/main/.github/assets/img/logo-small.png
